[package]
name = "linkbin"
version = "0.1.0"
authors = ["Harri Hämäläinen <hhamalai@iki.fi>"]

[dependencies]
rocket = "0.3.13"
rocket_codegen = "0.3.13"
rocket_contrib = "0.3.13"
nom = "^4.0"
chrono = { version = "0.4", features = ["serde"] }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

